title: [Review Agent]
description: Additional informations about our project.
theme: jekyll-theme-cayman # Możesz zmienić na: jekyll-theme-minimal, jekyll-theme-tactile
show_downloads: false
google_analytics: # Tu możesz wpisać ID, jeśli chcesz śledzić ile osób skanuje kod QR